#SingleInstance force
#Include C:\work-station\autohotkey-scripts\open-cmd.ahk
#Include C:\work-station\autohotkey-scripts\php-hotkey-$.ahk
#Include C:\work-station\autohotkey-scripts\autohotkey-command.ahk
#Include C:\work-station\autohotkey-scripts\special-character.ahk
#Include C:\work-station\autohotkey-scripts\useful-command.ahk
#Include C:\work-station\autohotkey-scripts\git-command.ahk
#Include C:\work-station\autohotkey-scripts\php-command.ahk
#Include C:\work-station\autohotkey-scripts\me.ahk
#Include C:\work-station\autohotkey-scripts\hint.ahk
#Include C:\work-station\autohotkey-scripts\server-command.ahk
#Include C:\work-station\autohotkey-scripts\mysql.ahk